const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorials'}],
  guideSidebar: [ // Új oldalsáv a guides-nak
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
};
module.exports = sidebars;